version: "3.9"
services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - selenium
    environment:
      - TZ=Asia/Shanghai
  selenium:
    image: "selenium/standalone-firefox:96.0"
    environment:
      - TZ=Asia/Shanghai
